In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.4319977 , 0.89785265, 0.57522785, 0.14781793, 0.70012227])

In [26]:
np.random.rand(5,5)

array([[0.16476004, 0.0589009 , 0.08174839, 0.44424209, 0.00163385],
       [0.46494682, 0.47335976, 0.87777845, 0.90864172, 0.92859014],
       [0.61938612, 0.23114373, 0.71461152, 0.557805  , 0.64282432],
       [0.92140695, 0.67331416, 0.16088666, 0.53080501, 0.78261868],
       [0.75129263, 0.05685605, 0.49628537, 0.06893766, 0.10508182]])

In [27]:
np.random.randn(2)

array([-0.70749306, -1.46958193])

In [29]:
np.random.randn(4,4)

array([[ 0.97245753, -2.41492652, -0.41484175,  0.45578171],
       [ 0.53137437,  0.4343258 ,  0.45905912, -0.15628641],
       [ 1.09235364, -1.32939771,  0.35178598, -0.18236665],
       [ 0.36157811,  0.19583527,  0.23269757, -1.89545249]])

In [32]:
np.random.randint(1,100,10)

array([40, 32, 84, 55, 32, 19, 33, 27, 99,  4])

In [36]:
np.random.randint(1,100,(4,4))

array([[34, 38, 86, 66],
       [25, 11, 41, 41],
       [78, 81, 27, 11],
       [37, 33, 55, 38]])

In [37]:
arr = np.arange(25)

In [38]:
ranarr = np.random.randint(1,100,10)

In [39]:
ranarr

array([53, 17,  4, 70, 81, 43, 44, 82, 81, 35])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.reshape(2,5)

array([[53, 17,  4, 70, 81],
       [43, 44, 82, 81, 35]])

In [42]:
ranarr.max()

82

In [43]:
ranarr.min()

4

In [44]:
ranarr.argmax()

7

In [45]:
ranarr.argmin()

2

In [46]:
arr.shape

(25,)

In [47]:
ranarr.shape

(10,)

In [48]:
arr.dtype

dtype('int32')

# NUMPY PRACTICE 

In [53]:
# ARRAY FUNCTION

In [55]:
import numpy as np

In [56]:
z1=[1,2,3,4,5,6,7,8,9,10]

In [57]:
np.array(z1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
z2=[[1,2,3],[4,5,6],[7,8,9]]

In [60]:
np.array(z2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# ARANGE FUNCTION

In [63]:
z3=np.arange(0,10)

In [64]:
z3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
z4=np.arange(0,21,2)

In [66]:
z5=np.arange(0,51,5)

In [67]:
z4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [68]:
z5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [69]:
z6=np.arange(21)

In [70]:
z6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [71]:
z7=np.arange(2,21,2)

In [72]:
z8=np.arange(5,51,5)

In [73]:
z7

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
z8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [76]:
# ZEROS FUNCTION

In [78]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
# ONES FUNCTION

In [84]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [85]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
# LINSPACE FUNCTION

In [103]:
z9 = np.linspace(0,50,25)
z9

array([ 0.        ,  2.08333333,  4.16666667,  6.25      ,  8.33333333,
       10.41666667, 12.5       , 14.58333333, 16.66666667, 18.75      ,
       20.83333333, 22.91666667, 25.        , 27.08333333, 29.16666667,
       31.25      , 33.33333333, 35.41666667, 37.5       , 39.58333333,
       41.66666667, 43.75      , 45.83333333, 47.91666667, 50.        ])

In [104]:
z10 = np.linspace(1,10,10)

In [105]:
z10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
z11=np.linspace(15,150,10)

In [101]:
z11

array([ 15.,  30.,  45.,  60.,  75.,  90., 105., 120., 135., 150.])

In [107]:
# EYE FUNCTION

In [108]:
np.eye(1)

array([[1.]])

In [109]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [110]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
# RANDOM LIBRARY FUNCTIONS

In [112]:
from numpy.random import rand

In [115]:
np.random.rand(10)

array([0.64630857, 0.92863193, 0.39120172, 0.98511423, 0.98653431,
       0.26874179, 0.45226337, 0.43572038, 0.25803708, 0.63285193])

In [116]:
np.random.rand(3,4)

array([[0.23002378, 0.7947032 , 0.44915664, 0.71212024],
       [0.04269558, 0.9542791 , 0.61666205, 0.7367527 ],
       [0.78509242, 0.32550058, 0.444562  , 0.17566112]])

In [117]:
np.random.rand(5,5)

array([[0.27620726, 0.19718967, 0.40103471, 0.95483482, 0.39085723],
       [0.33645747, 0.91249393, 0.59641862, 0.46310661, 0.94541389],
       [0.27193151, 0.35502619, 0.82119698, 0.76117313, 0.43243557],
       [0.66056519, 0.91251259, 0.02384484, 0.38435537, 0.42522368],
       [0.98323755, 0.43256872, 0.12960062, 0.74248447, 0.3666462 ]])

In [118]:
np.random.randn(10)

array([-0.52727639, -0.61102721, -0.19359427,  0.40284527, -1.11732012,
       -0.49087408, -0.28365077,  0.8551414 , -0.0853237 ,  1.16861751])

In [119]:
np.random.randn(5,5)

array([[ 0.73371512, -0.49068738, -0.10652266,  2.01240105, -0.5222934 ],
       [ 1.02997044,  0.40368393, -0.34586652, -0.13545441,  0.78402222],
       [ 0.34100848, -0.03884269,  0.02582296,  1.94436492,  0.56602743],
       [ 1.04244468, -1.55199682,  2.70170435, -0.07342859, -0.76326702],
       [ 0.62961271,  2.1961391 , -1.22441804, -1.0160442 , -1.28260474]])

In [124]:
np.random.randint(1,1000,50)

array([177, 852, 504, 817, 786, 106, 679, 643,  63, 883,  60, 433, 161,
       604, 110, 509,  37, 532, 881, 412, 250, 813, 485, 478, 140, 920,
       658, 497, 934, 530, 575, 405, 148, 960, 156, 383, 616, 992, 314,
       742, 883, 158, 637, 265, 882, 151, 376, 333, 674,  33])

In [131]:
np.random.randint(1,1000,(3,3))

array([[854, 145, 434],
       [289, 781, 935],
       [554, 564, 350]])

In [138]:
z12 = np.arange(162)

In [139]:
z12

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161])

In [141]:
z12.reshape(18,9)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62],
       [ 63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152],
       [153, 154, 155, 156, 157, 158, 159, 160, 161]])

In [144]:
z12.reshape(9,18)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
         31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
         49,  50,  51,  52,  53],
       [ 54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161]])

In [147]:
z12 = z12.reshape(2,81)

In [148]:
z12.shape

(2, 81)

In [150]:
ranarrr = np.random.randint(1,100,10)

In [152]:
ranarrr
np.random.seed(100)

In [154]:
ranarrr

array([61, 19, 40,  8, 54, 30, 22, 93, 21, 27])

In [153]:
ranarrr

array([61, 19, 40,  8, 54, 30, 22, 93, 21, 27])

In [156]:
ranarrr.max()

93

In [157]:
ranarrr.min()

8

In [158]:
ranarrr.argmax()

7

In [159]:
ranarrr.argmin()

3

In [160]:
ranarrr.shape

(10,)

In [161]:
ranarrr.dtype

dtype('int32')