In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice1 = arr[0:6]

In [14]:
slice1

array([0, 1, 2, 3, 4, 5])

In [15]:
slice1[:]

array([0, 1, 2, 3, 4, 5])

In [16]:
slice1[:] = 99

In [17]:
slice1

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:]  = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[1][1]

25

In [29]:
arr_2d[0][0]

5

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[2][1]

40

In [34]:
arr_2d[2,1]

40

In [35]:
arr_2d[1,2]

30

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [39]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [40]:
arr1 = np.arange(1,11)

In [41]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
bool1 = arr1 > 5

In [45]:
bool1

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr1[bool1]

array([ 6,  7,  8,  9, 10])

In [48]:
arr1[arr1>5]

array([ 6,  7,  8,  9, 10])

In [49]:
arr1[arr1<3]

array([1, 2])

# NUMPY PRACTICE

In [50]:
z = np.arange(1,11)

In [51]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
z[1]

2

In [53]:
z[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
z[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [55]:
z[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
z[3:7]

array([4, 5, 6, 7])

In [57]:
z[3:7] = 100

In [58]:
z

array([  1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [59]:
z

array([  1,   2,   3, 100, 100, 100, 100,   8,   9,  10])

In [66]:
slice2 = z[8:]

In [67]:
slice2

array([ 9, 10])

In [68]:
slice2[:] = 20

In [69]:
z

array([  1,   2,   3, 100, 100, 100, 100,   8,  20,  20])

In [71]:
k = np.arange(1,51).reshape(5,10)

In [72]:
k

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [74]:
l= np.array([ [4,8,12], [16, 20, 24], [28, 32, 36]])

In [75]:
l

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [76]:
l[1,2]

24

In [78]:
l[2][2]

36

In [80]:
l[1:,:2]

array([[16, 20],
       [28, 32]])

In [81]:
z

array([  1,   2,   3, 100, 100, 100, 100,   8,  20,  20])

In [82]:
z>10

array([False, False, False,  True,  True,  True,  True, False,  True,
        True])

In [84]:
z[z>10]

array([100, 100, 100, 100,  20,  20])

In [85]:
k

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [86]:
l

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [90]:
l[:2,1:]

array([[ 8, 12],
       [20, 24]])

In [91]:
k.shape

(5, 10)

In [92]:
k[3,8]

39

In [93]:
k[1:2,4:5]

array([[15]])